preload = ~/.wallpapers/aorus1.jpg
preload = ~/.wallpapers/cyber.jpg
preload = ~/.wallpapers/cyber2.jpg
preload = ~/.wallpapers/neonroom.jpg
preload = ~/.wallpapers/peakpx.jpg
preload = ~/.wallpapers/aloneman.jpg
preload = ~/.wallpapers/stay_cool.jpg
preload = ~/.wallpapers/vesseldove.jpg


wallpaper = eDP-1, ~/.wallpapers/vesseldove.jpg
wallpaper = DP-1, ~/.wallpapers/vesseldove.jpg
wallpaper = DP-2, ~/.wallpapers/vesseldove.jpg
